// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// read_trig //
// --------- //

#define read_trig_wrap_target 0
#define read_trig_wrap 3

static const uint16_t read_trig_program_instructions[] = {
            //     .wrap_target
    0x2080, //  0: wait   1 gpio, 0                  
    0xc020, //  1: irq    wait 0                     
    0x2000, //  2: wait   0 gpio, 0                  
    0xc021, //  3: irq    wait 1                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program read_trig_program = {
    .instructions = read_trig_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config read_trig_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + read_trig_wrap_target, offset + read_trig_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void read_trig_program_init(PIO pio, uint sm, uint offset) 
{    
    pio_sm_config c = read_trig_program_get_default_config(offset);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

